#:kivy 1.8.0

Screen:
	name: 'Settings'

	FloatLayout:
		Label:
			text: 'Media path'
			size_hint: (.4,.1)
			pos_hint: {'right':.5, 'y':.7}

		Label:
			text: './test'
			size_hint: (.4,.1)
			pos_hint: {'x':.5, 'y':.7}
		Label:
			text: 'Audiobook path'
			size_hint: (.4,.1)
			pos_hint: {'right':.5, 'y':.5}

		Label:
			text: './audiobooks'
			size_hint: (.4,.1)
			pos_hint: {'x':.5, 'y':.5}


	
